#! /bin/bash
LOG_FILE="./temperatures"

DATE=`date +"%y-%m-%d" | xargs echo -n`
DAY_LOG_FILE="${LOG_FILE}_${DATE}.csv"

# add CSV column description line,
# if the file do not already existing
if [ ! -f ${DAY_LOG_FILE} ]; then
	echo "Date;Set temp (in °C);Actual temp (in °C);Humidity (in %);Window" >> ${DAY_LOG_FILE}
fi

# write current date and remove new line
date +"%x %X" | xargs echo -n >> ${DAY_LOG_FILE}
echo -n ";" >> ${DAY_LOG_FILE}
wget -q -O- http://192.168.0.106/csv >> ${DAY_LOG_FILE}
# add a new line
echo >> ${DAY_LOG_FILE}
